services:
  images:
    build:
      context: .
      dockerfile: Fooocus.Dockerfile
    ports:
      - "7865:7865"
    volumes:
      - "./checkpoints/:/fooocus/models/checkpoints/"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]